server:
  port: ${SERVER_PORT:8066}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:autofix-demo-service}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:elk}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: always

app:
  environment: ${APP_ENVIRONMENT:local}

  logging:
    logstash:
      destination: ${LOGSTASH_DESTINATION:localhost:5000}
