input {
  tcp {
    id => "autofix-demo-tcp-input"
    host => "0.0.0.0"
    port => 5000
    codec => json_lines
  }
}

filter {
  if ![service] {
    mutate {
      add_field => {
        "service" => "unknown-service"
      }
    }
  }

  if ![environment] {
    mutate {
      add_field => {
        "environment" => "local"
      }
    }
  }
}

output {
  elasticsearch {
    id => "autofix-demo-elasticsearch-output"
    hosts => ["http://elasticsearch:9200"]
    index => "autofix-demo-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
